name: xtrabackup
base: core20 # core22 has openssl-3.x.x and xtrabackup require openssl-1.1.x
summary: Open source backup tool for InnoDB and XtraDB
description: |
  Open source backup tool for InnoDB and XtraDB
grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict
adopt-info: xtrabackup
environment:
  LD_LIBRARY_PATH: $SNAP/lib:$SNAP/usr/lib:$SNAP/usr/lib/x86_64-linux-gnu
  PATH: $SNAP/bin:$PATH
  LC_ALL: C

apps:
  xtrabackup:
    command: usr/bin/xtrabackup
    plugs:
      - network
      - removable-media
      - home
      - mysql-data
  xbcloud:
    command: usr/bin/xbcloud
    plugs:
      - network
      - removable-media
      - home
  xbcloud-osenv:
    command: usr/bin/xbcloud_osenv
    plugs:
      - network
      - removable-media
      - home
  xbcrypt:
    command: usr/bin/xbcrypt
    plugs:
      - network
      - removable-media
      - home
  xbstream:
    command: usr/bin/xbstream
    plugs:
      - network
      - removable-media
      - home

plugs:
  mysql-data:
    interface: system-files
    write:
      - /var/lib/mysql

parts:
  xtrabackup:
    plugin: cmake
    source: https://github.com/percona/percona-xtrabackup.git
    source-type: git
    source-tag: "percona-xtrabackup-8.0.30-23"
    cmake-parameters:
      - -DCMAKE_INSTALL_PREFIX=/usr
      - -DINSTALL_LAYOUT=DEB
      - -DBUILD_CONFIG=xtrabackup_release
      - -DCMAKE_BUILD_TYPE=Release
      - -DWITH_MAN_PAGES=OFF
      - -DIGNORE_AIO_CHECK=ON
      - -DWITH_AUTHENTICATION_FIDO=OFF
      - -DWITH_AUTHENTICATION_KERBEROS=OFF
      - -DWITH_AUTHENTICATION_LDAP=OFF
      - -DINSTALL_MYSQLTESTDIR= # empty to avoid install
      - -DINSTALL_MANDIR=
      - -DWITH_BOOST=$SNAPCRAFT_PART_BUILD/../../boost/src
    after: [boost]
    override-pull: |
      git clone --branch percona-xtrabackup-8.0.30-23 --depth 1 \
        https://github.com/percona/percona-xtrabackup.git .
      git submodule update --init
    override-build: |
      snapcraftctl build
      snapcraftctl set-version "8.0.30-23"
    override-prime: |
      snapcraftctl prime
      rm -rf $SNAPCRAFT_PRIME/usr/share
      rm -rf $SNAPCRAFT_PRIME/usr/include
      rm -rf $SNAPCRAFT_PRIME/man1
      rm -rf $SNAPCRAFT_PRIME/man8
      mv $SNAPCRAFT_PRIME/usr/bin/xtrabackup $SNAPCRAFT_PRIME/usr/bin/xtrabackup-bin
      cp $SNAPCRAFT_PROJECT_DIR/scripts/xtrabackup $SNAPCRAFT_PRIME/usr/bin/xtrabackup
    build-packages:
      - bison
      - cmake
      - g++
      - gcc
      - libcurl4
      - libcurl4-gnutls-dev
      - libev-dev
      - libgcrypt20-dev
      - libncurses5-dev
      - libprocps-dev
      - libssl-dev
      - pkg-config
      - xxd
    stage-packages:
      - libasn1-8-heimdal
      - libbrotli1
      - libcurl3-gnutls
      - libev4
      - libgssapi3-heimdal
      - libhcrypto4-heimdal
      - libheimbase1-heimdal
      - libheimntlm0-heimdal
      - libhx509-5-heimdal
      - libkrb5-26-heimdal
      - libldap-2.4-2
      - libnghttp2-14
      - libpsl5
      - libroken18-heimdal
      - librtmp1
      - libsasl2-2
      - libssh-4
      - libwind0-heimdal
  boost:
    plugin: dump
    source-type: tar
    source: https://boostorg.jfrog.io/artifactory/main/release/1.77.0/source/boost_1_77_0.tar.bz2
    override-build: ":" # Do nothing
    build-packages:
      - bzip2
